from __future__ import annotations

import argparse
from pathlib import Path
import pandas as pd


def table(path: Path, cols=None, round_digits=4) -> str:
    if not path.exists():
        return f'_Missing: `{path.name}`_'
    df = pd.read_csv(path)
    if cols:
        df = df[[c for c in cols if c in df.columns]]
    num = df.select_dtypes(include='number').columns
    if len(num):
        df[num] = df[num].round(round_digits)
    return df.to_markdown(index=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--root', default='data/cafef_multiyear')
    args = parser.parse_args()
    root = Path(args.root).resolve()
    out = root / 'analysis_multiyear'
    periods = ['2019-10', '2020-10', '2021-10', '2022-10']
    lines = [
        '# Multi-year FinABSA--CafeF financial validation report',
        '',
        'This report combines four period-specific runs. Each October period is validated independently using its own May--December price window and VNINDEX market model. The tables are pooled for comparison only; they are not a pooled causal panel estimate.',
        '',
        '## 1. Prediction validation',
        '',
        table(out / 'prediction_validation_by_period.csv'),
        '',
        'All periods have complete input--prediction alignment, zero missing predictions, zero unexpected IDs, zero duplicate IDs, and zero unknown labels after normalization.',
        '',
        '## 2. Event-study CAR tests',
        '',
        table(out / 'car_tests.csv', ['period','window','group','n','mean_car','median_car','t_p','sign_flip_p','bootstrap_ci_low','bootstrap_ci_high']),
        '',
        'The `All` rows are the primary aggregate CAR tests. Group rows are descriptive/inferential comparisons within each period and should be interpreted cautiously because positive and negative groups are small.',
        '',
        '## 3. News-day versus no-news-day control',
        '',
        table(out / 'news_day_control_tests.csv'),
        '',
        'The control comparison is restricted to eligible ticker--days and tests whether abnormal returns differ when an identified news event is present.',
        '',
        '## 4. Sentiment-group contrasts',
        '',
        table(out / 'sentiment_group_tests.csv'),
        '',
        'Differences are defined as group A minus group B. Welch, permutation, and bootstrap results are reported together so that conclusions do not depend on a single parametric assumption.',
        '',
        '## 5. Two-way fixed-effects panel coefficients',
        '',
        table(out / 'panel_regression_coefficients.csv', ['period','Unnamed: 0','coef','std_err','p_value']),
        '',
        'Each period uses ticker and date fixed effects. The sparse-panel covariance fallback, where applicable, is documented in the period-specific `panel_regression.txt` file.',
        '',
        '## 6. Lag robustness',
        '',
        table(out / 'robustness_summary.csv', ['period','design','lag','n','mean_ar','median_ar','negative_mean_ar','neutral_mean_ar','positive_mean_ar']),
        '',
        'Lag estimates are sensitivity checks. A changing sample size and changing point estimates across lags weaken any claim of a stable delayed sentiment effect.',
        '',
        '## 7. Additional complete tables',
        '',
    ]
    for name in ['event_summary_by_label.csv','panel_summary_by_label.csv','daily_market_sentiment.csv','market_models.csv','event_observations.csv','panel_regression_data.csv']:
        lines += [f'### `{name}`', '', table(out / name), '']
    lines += [
        '## 8. Interpretation and limitations',
        '',
        'The analysis supports the technical validity of the end-to-end pipeline, not a causal claim that news sentiment moves stock prices. The four periods differ in article coverage, entity-linking yield, ticker availability, and class balance. Cross-year comparisons should therefore report sample sizes and price coverage next to every estimate. The model outputs are hard labels without calibrated probabilities, so intrinsic accuracy and calibration cannot be inferred from this run.',
        '',
        'Generated by `run_multiyear_pipeline.py` and `build_multiyear_report.py`.',
    ]
    path = out / 'multiyear_report_complete.md'
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'saved={path}')


if __name__ == '__main__':
    main()
