import torch
import pandas as pd
import argparse
import re
import numpy as np
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, DataCollatorForSeq2Seq
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm
import evaluate
from collections import Counter
from sklearn.metrics import accuracy_score, f1_score, classification_report

def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate trained T5 model on saved test set")
    parser.add_argument("--model_dir", default="/home/huylkq/repos/nlp/FinABSA-Valid/MODEL/FinABSA",
    # parser.add_argument("--model_dir", default="./MODEL/finabsa-other-masked-final",
                        help="Path to saved model")
    parser.add_argument("--test_csv", default="/home/huylkq/repos/nlp/FinABSA-Valid/finabsa_10%.csv",
    # parser.add_argument("--test_csv", default="test_set.csv",
                        help="CSV file with tokenized test set (generated by train script)")
    parser.add_argument("--batch_size", type=int, default=128,
                        help="Batch size for generation")
    parser.add_argument("--max_output_length", type=int, default=20,
                        help="Maximum generation length")
    parser.add_argument("--num_beams", type=int, default=4,
                        help="Number of beams for beam search")
    return parser.parse_args()

class TestDataset(Dataset):
    def __init__(self, df):
        self.input_texts = df["input"].tolist()
        self.output_texts = df["output"].tolist()
        self.input_ids = [list(map(int, x.split())) for x in df["input_ids"]]
        self.labels = [list(map(int, x.split())) for x in df["labels"]]

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            "input_ids": self.input_ids[idx],
            "labels": self.labels[idx],
        }

# ---------- Hàm trích xuất sentiment từ văn bản ----------
def extract_sentiment(text: str) -> str:
    """
    Trích xuất nhãn sentiment (POSITIVE/NEGATIVE/NEUTRAL) từ câu văn bản.
    Tìm kiếm không phân biệt hoa/thường, hỗ trợ nhiều định dạng.
    """
    # Chuyển về chữ thường để so sánh dễ dàng
    text_lower = text.lower()
    
    # Tìm từ khóa sentiment
    if 'positive' in text_lower:
        return "POSITIVE"
    elif 'negative' in text_lower:
        return "NEGATIVE"
    elif 'neutral' in text_lower:
        return "NEUTRAL"
    else:
        # Nếu không tìm thấy, trả về NEUTRAL
        return "UNKNOW"

# ---------- Hàm tính Exact Match và Token F1 ----------
def exact_match(pred: str, ref: str) -> int:
    return int(pred.strip() == ref.strip())

def token_f1(pred: str, ref: str) -> float:
    pred_tokens = pred.strip().split()
    ref_tokens = ref.strip().split()
    if not pred_tokens and not ref_tokens:
        return 1.0
    if not pred_tokens or not ref_tokens:
        return 0.0
    common = Counter(pred_tokens) & Counter(ref_tokens)
    num_same = sum(common.values())
    if num_same == 0:
        return 0.0
    precision = num_same / len(pred_tokens)
    recall = num_same / len(ref_tokens)
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    return f1

def main():
    args = parse_args()

    # Load model & tokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.model_dir)
    model = AutoModelForSeq2SeqLM.from_pretrained(args.model_dir)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()
    print(f"Model loaded on {device}")

    # Đọc test set tokenized
    df = pd.read_csv(args.test_csv)
    print(f"Loaded test set with {len(df)} samples")

    test_dataset = TestDataset(df)
    data_collator = DataCollatorForSeq2Seq(tokenizer, model=model, padding=True)

    dataloader = DataLoader(
        test_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        collate_fn=data_collator
    )

    all_input_texts = test_dataset.input_texts
    all_output_texts = test_dataset.output_texts

    predictions = []
    references = []
    input_texts = []

    idx = 0
    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Generating"):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            outputs = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_length=args.max_output_length,
                num_beams=args.num_beams,
                early_stopping=True
            )
            decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)
            batch_size = len(decoded)
            predictions.extend(decoded)
            references.extend(all_output_texts[idx:idx+batch_size])
            input_texts.extend(all_input_texts[idx:idx+batch_size])
            idx += batch_size

    # ---------- Tính ROUGE, BLEU (các metric truyền thống) ----------
    try:
        rouge = evaluate.load('rouge')
        bleu = evaluate.load('bleu')
        rouge_score = rouge.compute(predictions=predictions, references=references)
        bleu_score = bleu.compute(predictions=predictions, references=references)
        print("\n--- GENERATION METRICS ---")
        print(f"ROUGE-1: {rouge_score['rouge1']:.4f}")
        print(f"ROUGE-2: {rouge_score['rouge2']:.4f}")
        print(f"ROUGE-L: {rouge_score['rougeL']:.4f}")
        print(f"BLEU:    {bleu_score['bleu']:.4f}")
    except ImportError:
        print("Install 'evaluate' and 'rouge-score' to get ROUGE/BLEU")
        rouge_score = {}
        bleu_score = {}

    # ---------- Tính Exact Match và Token F1 ----------
    em_scores = []
    f1_scores = []
    for pred, ref in zip(predictions, references):
        em_scores.append(exact_match(pred, ref))
        f1_scores.append(token_f1(pred, ref))

    avg_em = np.mean(em_scores)
    avg_f1 = np.mean(f1_scores)
    print(f"Exact Match (EM): {avg_em:.4f}")
    print(f"Token F1 (macro): {avg_f1:.4f}")

    # ---------- TRÍCH XUẤT SENTIMENT VÀ TÍNH ACC/F1 ----------
    y_true_sent = [extract_sentiment(ref) for ref in references]
    y_pred_sent = [extract_sentiment(pred) for pred in predictions]

    # Tính các chỉ số phân loại
    accuracy = accuracy_score(y_true_sent, y_pred_sent)
    f1_macro = f1_score(y_true_sent, y_pred_sent, average='macro', labels=['POSITIVE','NEGATIVE','NEUTRAL'])
    f1_weighted = f1_score(y_true_sent, y_pred_sent, average='weighted', labels=['POSITIVE','NEGATIVE','NEUTRAL'])

    print("\n--- SENTIMENT CLASSIFICATION METRICS ---")
    print(f"Accuracy:          {accuracy:.4f}")
    print(f"F1-macro:          {f1_macro:.4f}")
    print(f"F1-weighted:       {f1_weighted:.4f}")

    # In báo cáo chi tiết từng lớp
    report = classification_report(y_true_sent, y_pred_sent, labels=['POSITIVE','NEGATIVE','NEUTRAL'], zero_division=0)
    print("\nDetailed Classification Report:\n")
    print(report)

    # Lưu kết quả chi tiết từng mẫu (bao gồm cả sentiment)
    result_df = pd.DataFrame({
        "input": input_texts,
        "label": references,
        "prediction": predictions,
        "label_sentiment": y_true_sent,
        "pred_sentiment": y_pred_sent,
        "exact_match": em_scores,
        "token_f1": f1_scores
    })
    result_df.to_csv("test_predictions.csv", index=False)
    print("\nDetailed predictions saved to test_predictions.csv")

    # ---------- Lưu bảng tổng kết tất cả metrics ----------
    metrics_summary = {
        "metric": [
            "ROUGE-1", "ROUGE-2", "ROUGE-L", "BLEU",
            "Exact Match", "Token F1",
            "Accuracy (sentiment)", "F1-macro (sentiment)", "F1-weighted (sentiment)"
        ],
        "score": [
            f"{rouge_score.get('rouge1', 0.0):.4f}",
            f"{rouge_score.get('rouge2', 0.0):.4f}",
            f"{rouge_score.get('rougeL', 0.0):.4f}",
            f"{bleu_score.get('bleu', 0.0):.4f}",
            f"{avg_em:.4f}",
            f"{avg_f1:.4f}",
            f"{accuracy:.4f}",
            f"{f1_macro:.4f}",
            f"{f1_weighted:.4f}"
        ]
    }
    summary_df = pd.DataFrame(metrics_summary)
    summary_df.to_csv("metrics_summary.csv", index=False)
    print("Metrics summary saved to metrics_summary.csv")

if __name__ == "__main__":
    main()